typography_spectrum: 0.39577332755476835
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.4455214494366372
  lightness: 0.9592477016019045
  saturation: 0.6734701812351283
  rhythmicContrast: 0.872938731653428
layout_spectrum: 0.08645682884123351
author:
  email: ericsantiago@question-modern.com
name: Questioning Modernity
navigation:
  - name: Twitter
    url: 'https://twitter.com/QuestionModern'
    type: external
  - name: Contact me
    id: 894d7d24-7a5b-45ea-966d-03fa48cf96c2
    type: content
title: Questioning Modernity
