typography_spectrum: 0.39577332755476835
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.4455214494366372
  lightness: 0.9592477016019045
  saturation: 0.6734701812351283
  rhythmicContrast: 0.872938731653428
layout_spectrum: 0.08645682884123351
analytics:
  google: UA-82814981-1
author:
  email: ericsantiago@question-modernity.com
  name: Eric Santiago
  url: question-modernity.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/720aeb86-2adc-4756-819d-60231570c229.jpg
name: Questioning Modernity
navigation:
  - name: Twitter
    url: 'https://twitter.com/QuestionModern'
    type: external
  - name: Contact me
    id: 894d7d24-7a5b-45ea-966d-03fa48cf96c2
    type: content
  - name: Advice for Students
    id: 55af0d3a-c117-4757-9657-59ca8e20c089
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/772659af-9904-4710-a4d9-0c432452876a.jpg
title: Questioning Modernity
